services:
  - type: web
    name: shared-ar-workshop-api
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
